### DISCUSSION TITLE
Groq: remove model Meta Llama 3.1 70B Versatile

### DISCUSSION THREAD

**Discussion by lumpidu** [AllYourBot/hostedgpt#611] [General]
Hi,

just tried the Groq integration with the above model: this seems to be deprecated:

![grafik](https://github.com/user-attachments/assets/4e40d49d-5d85-4bb0-b661-eb2c4a05818e)

But there is now available deepseek-r1-distill-llama-70B, which is extremely powerful. Would that be possible to switch that over ?

**Comment by lumpidu** [comment]
It seems these are the right settings for `models.yml` for the new Groq models:

```yaml
- api_name: deepseek-r1-distill-llama-70B
  name: DeepSeek R1 Distill Llama 70B
  supports_images: false
  supports_tools: false
  input_token_cost_cents: '0.000075'
  output_token_cost_cents: '0.000099'
  best: true
  supports_system_message: true
  api_service_name: Groq
- api_name: llama-3.3-70b-versatile
  name: Llama 3.3 70B Versatile 128k
  supports_images: false
  supports_tools: false
  input_token_cost_cents: '0.000059'
  output_token_cost_cents: '0.000079'
  best: true
  supports_system_message: true
  api_service_name: Groq
```
